apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail
  template:
    metadata:
      labels:
        app: mail
    spec:
      containers:
        - name: mail
          image: racf3008/mail
          env:
            - name: EMAIL_ADDR
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: address
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: password
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: greenhive
            - name: MAIL_PASS
              value: 'greenHiveMailer2024'
            - name: MONGO_URI
              value: 'mongodb://mail-mongo-srv:27017/mail'
---
apiVersion: v1
kind: Service
metadata:
  name: mail-srv
spec:
  selector:
    app: mail
  type: ClusterIP
  ports:
    - name: mail
      protocol: TCP
      port: 3000
      targetPort: 3000
