apiVersion: apps/v1
kind: Deployment
metadata:
  name: readings-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readings
  template:
    metadata:
      labels:
        app: readings
    spec:
      containers:
        - name: readings
          image: racf3008/readings
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: greenhive
            - name: MONGO_URI
              value: 'mongodb://readings-mongo-srv:27017/readings'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: readings-srv
spec:
  selector:
    app: readings
  type: ClusterIP
  ports:
    - name: readings
      protocol: TCP
      port: 3000
      targetPort: 3000
