apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokens-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tokens
  template:
    metadata:
      labels:
        app: tokens
    spec:
      containers:
        - name: tokens
          image: racf3008/tokens
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: greenhive
            - name: MONGO_URI
              value: 'mongodb://tokens-mongo-srv:27017/tokens'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: tokens-srv
spec:
  selector:
    app: tokens
  type: ClusterIP
  ports:
    - name: tokens
      protocol: TCP
      port: 3000
      targetPort: 3000
