name: tests-commands

on:
  pull_request:
    paths:
      - "commands/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd commands && npm install && npm run test:ci
